var THREE=THREE||{};if(!window.Int32Array)window.Int32Array=Array,window.Float32Array=Array;THREE.Color=function(a){a!==void 0&&this.setHex(a);return this};
THREE.Color.prototype={constructor:THREE.Color,r:1,g:1,b:1,copy:function(a){this.r=a.r;this.g=a.g;this.b=a.b;return this},setRGB:function(a,b,c){this.r=a;this.g=b;this.b=c;return this},setHSV:function(a,b,c){var d,f,e;if(c==0)this.r=this.g=this.b=0;else switch(d=Math.floor(a*6),f=a*6-d,a=c*(1-b),e=c*(1-b*f),b=c*(1-b*(1-f)),d){case 1:this.r=e;this.g=c;this.b=a;break;case 2:this.r=a;this.g=c;this.b=b;break;case 3:this.r=a;this.g=e;this.b=c;break;case 4:this.r=b;this.g=a;this.b=c;break;case 5:this.r=
c;this.g=a;this.b=e;break;case 6:case 0:this.r=c,this.g=b,this.b=a}return this},setHex:function(a){a=Math.floor(a);this.r=(a>>16&255)/255;this.g=(a>>8&255)/255;this.b=(a&255)/255;return this},getHex:function(){return~~(this.r*255)<<16^~~(this.g*255)<<8^~~(this.b*255)},getContextStyle:function(){return"rgb("+Math.floor(this.r*255)+","+Math.floor(this.g*255)+","+Math.floor(this.b*255)+")"},clone:function(){return(new THREE.Color).setRGB(this.r,this.g,this.b)}};
THREE.Vector2=function(a,b){this.x=a||0;this.y=b||0};
THREE.Vector2.prototype={constructor:THREE.Vector2,set:function(a,b){this.x=a;this.y=b;return this},copy:function(a){this.x=a.x;this.y=a.y;return this},clone:function(){return new THREE.Vector2(this.x,this.y)},add:function(a,b){this.x=a.x+b.x;this.y=a.y+b.y;return this},addSelf:function(a){this.x+=a.x;this.y+=a.y;return this},sub:function(a,b){this.x=a.x-b.x;this.y=a.y-b.y;return this},subSelf:function(a){this.x-=a.x;this.y-=a.y;return this},multiplyScalar:function(a){this.x*=a;this.y*=a;return this},
divideScalar:function(a){a?(this.x/=a,this.y/=a):this.set(0,0);return this},negate:function(){return this.multiplyScalar(-1)},dot:function(a){return this.x*a.x+this.y*a.y},lengthSq:function(){return this.x*this.x+this.y*this.y},length:function(){return Math.sqrt(this.lengthSq())},normalize:function(){return this.divideScalar(this.length())},distanceTo:function(a){return Math.sqrt(this.distanceToSquared(a))},distanceToSquared:function(a){var b=this.x-a.x,a=this.y-a.y;return b*b+a*a},setLength:function(a){return this.normalize().multiplyScalar(a)},
equals:function(a){return a.x==this.x&&a.y==this.y}};THREE.Vector3=function(a,b,c){this.x=a||0;this.y=b||0;this.z=c||0};
THREE.Vector3.prototype={constructor:THREE.Vector3,set:function(a,b,c){this.x=a;this.y=b;this.z=c;return this},copy:function(a){this.x=a.x;this.y=a.y;this.z=a.z;return this},clone:function(){return new THREE.Vector3(this.x,this.y,this.z)},add:function(a,b){this.x=a.x+b.x;this.y=a.y+b.y;this.z=a.z+b.z;return this},addSelf:function(a){this.x+=a.x;this.y+=a.y;this.z+=a.z;return this},addScalar:function(a){this.x+=a;this.y+=a;this.z+=a;return this},sub:function(a,b){this.x=a.x-b.x;this.y=a.y-b.y;this.z=
a.z-b.z;return this},subSelf:function(a){this.x-=a.x;this.y-=a.y;this.z-=a.z;return this},multiply:function(a,b){this.x=a.x*b.x;this.y=a.y*b.y;this.z=a.z*b.z;return this},multiplySelf:function(a){this.x*=a.x;this.y*=a.y;this.z*=a.z;return this},multiplyScalar:function(a){this.x*=a;this.y*=a;this.z*=a;return this},divideSelf:function(a){this.x/=a.x;this.y/=a.y;this.z/=a.z;return this},divideScalar:function(a){a?(this.x/=a,this.y/=a,this.z/=a):this.set(0,0,0);return this},negate:function(){return this.multiplyScalar(-1)},
dot:function(a){return this.x*a.x+this.y*a.y+this.z*a.z},lengthSq:function(){return this.x*this.x+this.y*this.y+this.z*this.z},length:function(){return Math.sqrt(this.lengthSq())},lengthManhattan:function(){return this.x+this.y+this.z},normalize:function(){return this.divideScalar(this.length())},setLength:function(a){return this.normalize().multiplyScalar(a)},cross:function(a,b){this.x=a.y*b.z-a.z*b.y;this.y=a.z*b.x-a.x*b.z;this.z=a.x*b.y-a.y*b.x;return this},crossSelf:function(a){return this.set(this.y*
a.z-this.z*a.y,this.z*a.x-this.x*a.z,this.x*a.y-this.y*a.x)},distanceTo:function(a){return Math.sqrt(this.distanceToSquared(a))},distanceToSquared:function(a){return(new THREE.Vector3).sub(this,a).lengthSq()},setPositionFromMatrix:function(a){this.x=a.n14;this.y=a.n24;this.z=a.n34},setRotationFromMatrix:function(a){var b=Math.cos(this.y);this.y=Math.asin(a.n13);Math.abs(b)>1.0E-5?(this.x=Math.atan2(-a.n23/b,a.n33/b),this.z=Math.atan2(-a.n12/b,a.n11/b)):(this.x=0,this.z=Math.atan2(a.n21,a.n22))},isZero:function(){return this.lengthSq()<
1.0E-4}};THREE.Vector4=function(a,b,c,d){this.x=a||0;this.y=b||0;this.z=c||0;this.w=d||1};
THREE.Vector4.prototype={constructor:THREE.Vector4,set:function(a,b,c,d){this.x=a;this.y=b;this.z=c;this.w=d;return this},copy:function(a){this.x=a.x;this.y=a.y;this.z=a.z;this.w=a.w||1},clone:function(){return new THREE.Vector4(this.x,this.y,this.z,this.w)},add:function(a,b){this.x=a.x+b.x;this.y=a.y+b.y;this.z=a.z+b.z;this.w=a.w+b.w;return this},addSelf:function(a){this.x+=a.x;this.y+=a.y;this.z+=a.z;this.w+=a.w;return this},sub:function(a,b){this.x=a.x-b.x;this.y=a.y-b.y;this.z=a.z-b.z;this.w=
a.w-b.w;return this},subSelf:function(a){this.x-=a.x;this.y-=a.y;this.z-=a.z;this.w-=a.w;return this},multiplyScalar:function(a){this.x*=a;this.y*=a;this.z*=a;this.w*=a;return this},divideScalar:function(a){a?(this.x/=a,this.y/=a,this.z/=a,this.w/=a):(this.z=this.y=this.x=0,this.w=1);return this},negate:function(){return this.multiplyScalar(-1)},dot:function(a){return this.x*a.x+this.y*a.y+this.z*a.z+this.w*a.w},lengthSq:function(){return this.dot(this)},length:function(){return Math.sqrt(this.lengthSq())},
normalize:function(){return this.divideScalar(this.length())},setLength:function(a){return this.normalize().multiplyScalar(a)},lerpSelf:function(a,b){this.x+=(a.x-this.x)*b;this.y+=(a.y-this.y)*b;this.z+=(a.z-this.z)*b;this.w+=(a.w-this.w)*b;return this}};THREE.Ray=function(a,b){this.origin=a||new THREE.Vector3;this.direction=b||new THREE.Vector3};
THREE.Ray.prototype={constructor:THREE.Ray,intersectScene:function(a){return this.intersectObjects(a.objects)},intersectObjects:function(a){var b,c,d=[];b=0;for(c=a.length;b<c;b++)d=d.concat(this.intersectObject(a[b]));d.sort(function(a,b){return a.distance-b.distance});return d},intersectObject:function(a){function b(a,b,c){var d;d=c.clone().subSelf(a).dot(b);if(d<=0)return null;a=a.clone().addSelf(b.clone().multiplyScalar(d));return c.distanceTo(a)}function c(a,b,c,d){var d=d.clone().subSelf(b),
c=c.clone().subSelf(b),f=a.clone().subSelf(b),a=d.dot(d),b=d.dot(c),d=d.dot(f),e=c.dot(c),c=c.dot(f),f=1/(a*e-b*b),e=(e*d-b*c)*f,a=(a*c-b*d)*f;return e>0&&a>0&&e+a<1}if(a instanceof THREE.Particle){var d=b(this.origin,this.direction,a.matrixWorld.getPosition());return d==null||d>a.scale.x?[]:[{distance:d,point:a.position,face:null,object:a}]}else if(a instanceof THREE.Mesh){d=b(this.origin,this.direction,a.matrixWorld.getPosition());if(d==null||d>a.geometry.boundingSphere.radius*Math.max(a.scale.x,
Math.max(a.scale.y,a.scale.z)))return[];var f,e,g,h,k,m,o,i,j,l,p=a.geometry,q=p.vertices,r=[],d=0;for(f=p.faces.length;d<f;d++)if(e=p.faces[d],j=this.origin.clone(),l=this.direction.clone(),m=a.matrixWorld,g=m.multiplyVector3(e.centroid.clone()).subSelf(j),i=g.dot(l),!(i<=0)&&(g=m.multiplyVector3(q[e.a].position.clone()),h=m.multiplyVector3(q[e.b].position.clone()),k=m.multiplyVector3(q[e.c].position.clone()),m=e instanceof THREE.Face4?m.multiplyVector3(q[e.d].position.clone()):null,o=a.matrixRotationWorld.multiplyVector3(e.normal.clone()),
i=l.dot(o),a.doubleSided||(a.flipSided?i>0:i<0)))if(i=o.dot((new THREE.Vector3).sub(g,j))/i,j=j.addSelf(l.multiplyScalar(i)),e instanceof THREE.Face3)c(j,g,h,k)&&(e={distance:this.origin.distanceTo(j),point:j,face:e,object:a},r.push(e));else if(e instanceof THREE.Face4&&(c(j,g,h,m)||c(j,h,k,m)))e={distance:this.origin.distanceTo(j),point:j,face:e,object:a},r.push(e);r.sort(function(a,b){return a.distance-b.distance});return r}else return[]}};
THREE.Rectangle=function(){function a(){e=d-b;g=f-c}var b,c,d,f,e,g,h=!0;this.getX=function(){return b};this.getY=function(){return c};this.getWidth=function(){return e};this.getHeight=function(){return g};this.getLeft=function(){return b};this.getTop=function(){return c};this.getRight=function(){return d};this.getBottom=function(){return f};this.set=function(e,g,o,i){h=!1;b=e;c=g;d=o;f=i;a()};this.addPoint=function(e,g){h?(h=!1,b=e,c=g,d=e,f=g):(b=b<e?b:e,c=c<g?c:g,d=d>e?d:e,f=f>g?f:g);a()};this.add3Points=
function(e,g,o,i,j,l){h?(h=!1,b=e<o?e<j?e:j:o<j?o:j,c=g<i?g<l?g:l:i<l?i:l,d=e>o?e>j?e:j:o>j?o:j,f=g>i?g>l?g:l:i>l?i:l):(b=e<o?e<j?e<b?e:b:j<b?j:b:o<j?o<b?o:b:j<b?j:b,c=g<i?g<l?g<c?g:c:l<c?l:c:i<l?i<c?i:c:l<c?l:c,d=e>o?e>j?e>d?e:d:j>d?j:d:o>j?o>d?o:d:j>d?j:d,f=g>i?g>l?g>f?g:f:l>f?l:f:i>l?i>f?i:f:l>f?l:f);a()};this.addRectangle=function(e){h?(h=!1,b=e.getLeft(),c=e.getTop(),d=e.getRight(),f=e.getBottom()):(b=b<e.getLeft()?b:e.getLeft(),c=c<e.getTop()?c:e.getTop(),d=d>e.getRight()?d:e.getRight(),f=f>
e.getBottom()?f:e.getBottom());a()};this.inflate=function(e){b-=e;c-=e;d+=e;f+=e;a()};this.minSelf=function(e){b=b>e.getLeft()?b:e.getLeft();c=c>e.getTop()?c:e.getTop();d=d<e.getRight()?d:e.getRight();f=f<e.getBottom()?f:e.getBottom();a()};this.instersects=function(a){return Math.min(d,a.getRight())-Math.max(b,a.getLeft())>=0&&Math.min(f,a.getBottom())-Math.max(c,a.getTop())>=0};this.empty=function(){h=!0;f=d=c=b=0;a()};this.isEmpty=function(){return h}};THREE.Matrix3=function(){this.m=[]};
THREE.Matrix3.prototype={constructor:THREE.Matrix3,transpose:function(){var a,b=this.m;a=b[1];b[1]=b[3];b[3]=a;a=b[2];b[2]=b[6];b[6]=a;a=b[5];b[5]=b[7];b[7]=a;return this},transposeIntoArray:function(a){var b=this.m;a[0]=b[0];a[1]=b[3];a[2]=b[6];a[3]=b[1];a[4]=b[4];a[5]=b[7];a[6]=b[2];a[7]=b[5];a[8]=b[8];return this}};THREE.Matrix4=function(a,b,c,d,f,e,g,h,k,m,o,i,j,l,p,q){this.set(a||1,b||0,c||0,d||0,f||0,e||1,g||0,h||0,k||0,m||0,o||1,i||0,j||0,l||0,p||0,q||1);this.flat=Array(16);this.m33=new THREE.Matrix3};
THREE.Matrix4.prototype={constructor:THREE.Matrix4,set:function(a,b,c,d,f,e,g,h,k,m,o,i,j,l,p,q){this.n11=a;this.n12=b;this.n13=c;this.n14=d;this.n21=f;this.n22=e;this.n23=g;this.n24=h;this.n31=k;this.n32=m;this.n33=o;this.n34=i;this.n41=j;this.n42=l;this.n43=p;this.n44=q;return this},identity:function(){this.set(1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1);return this},copy:function(a){this.set(a.n11,a.n12,a.n13,a.n14,a.n21,a.n22,a.n23,a.n24,a.n31,a.n32,a.n33,a.n34,a.n41,a.n42,a.n43,a.n44);return this},lookAt:function(a,
b,c){var d=THREE.Matrix4.__v1,f=THREE.Matrix4.__v2,e=THREE.Matrix4.__v3;e.sub(a,b).normalize();if(e.length()===0)e.z=1;d.cross(c,e).normalize();d.length()===0&&(e.x+=1.0E-4,d.cross(c,e).normalize());f.cross(e,d).normalize();this.n11=d.x;this.n12=f.x;this.n13=e.x;this.n21=d.y;this.n22=f.y;this.n23=e.y;this.n31=d.z;this.n32=f.z;this.n33=e.z;return this},multiplyVector3:function(a){var b=a.x,c=a.y,d=a.z,f=1/(this.n41*b+this.n42*c+this.n43*d+this.n44);a.x=(this.n11*b+this.n12*c+this.n13*d+this.n14)*f;
a.y=(this.n21*b+this.n22*c+this.n23*d+this.n24)*f;a.z=(this.n31*b+this.n32*c+this.n33*d+this.n34)*f;return a},multiplyVector4:function(a){var b=a.x,c=a.y,d=a.z,f=a.w;a.x=this.n11*b+this.n12*c+this.n13*d+this.n14*f;a.y=this.n21*b+this.n22*c+this.n23*d+this.n24*f;a.z=this.n31*b+this.n32*c+this.n33*d+this.n34*f;a.w=this.n41*b+this.n42*c+this.n43*d+this.n44*f;return a},rotateAxis:function(a){var b=a.x,c=a.y,d=a.z;a.x=b*this.n11+c*this.n12+d*this.n13;a.y=b*this.n21+c*this.n22+d*this.n23;a.z=b*this.n31+
c*this.n32+d*this.n33;a.normalize();return a},crossVector:function(a){var b=new THREE.Vector4;b.x=this.n11*a.x+this.n12*a.y+this.n13*a.z+this.n14*a.w;b.y=this.n21*a.x+this.n22*a.y+this.n23*a.z+this.n24*a.w;b.z=this.n31*a.x+this.n32*a.y+this.n33*a.z+this.n34*a.w;b.w=a.w?this.n41*a.x+this.n42*a.y+this.n43*a.z+this.n44*a.w:1;return b},multiply:function(a,b){var c=a.n11,d=a.n12,f=a.n13,e=a.n14,g=a.n21,h=a.n22,k=a.n23,m=a.n24,o=a.n31,i=a.n32,j=a.n33,l=a.n34,p=a.n41,q=a.n42,r=a.n43,v=a.n44,V=b.n11,x=b.n12,
Q=b.n13,y=b.n14,C=b.n21,n=b.n22,t=b.n23,u=b.n24,E=b.n31,T=b.n32,ba=b.n33,H=b.n34,N=b.n41,I=b.n42,M=b.n43,F=b.n44;this.n11=c*V+d*C+f*E+e*N;this.n12=c*x+d*n+f*T+e*I;this.n13=c*Q+d*t+f*ba+e*M;this.n14=c*y+d*u+f*H+e*F;this.n21=g*V+h*C+k*E+m*N;this.n22=g*x+h*n+k*T+m*I;this.n23=g*Q+h*t+k*ba+m*M;this.n24=g*y+h*u+k*H+m*F;this.n31=o*V+i*C+j*E+l*N;this.n32=o*x+i*n+j*T+l*I;this.n33=o*Q+i*t+j*ba+l*M;this.n34=o*y+i*u+j*H+l*F;this.n41=p*V+q*C+r*E+v*N;this.n42=p*x+q*n+r*T+v*I;this.n43=p*Q+q*t+r*ba+v*M;this.n44=
p*y+q*u+r*H+v*F;return this},multiplyToArray:function(a,b,c){this.multiply(a,b);c[0]=this.n11;c[1]=this.n21;c[2]=this.n31;c[3]=this.n41;c[4]=this.n12;c[5]=this.n22;c[6]=this.n32;c[7]=this.n42;c[8]=this.n13;c[9]=this.n23;c[10]=this.n33;c[11]=this.n43;c[12]=this.n14;c[13]=this.n24;c[14]=this.n34;c[15]=this.n44;return this},multiplySelf:function(a){this.multiply(this,a);return this},multiplyScalar:function(a){this.n11*=a;this.n12*=a;this.n13*=a;this.n14*=a;this.n21*=a;this.n22*=a;this.n23*=a;this.n24*=
a;this.n31*=a;this.n32*=a;this.n33*=a;this.n34*=a;this.n41*=a;this.n42*=a;this.n43*=a;this.n44*=a;return this},determinant:function(){var a=this.n11,b=this.n12,c=this.n13,d=this.n14,f=this.n21,e=this.n22,g=this.n23,h=this.n24,k=this.n31,m=this.n32,o=this.n33,i=this.n34,j=this.n41,l=this.n42,p=this.n43,q=this.n44;return d*g*m*j-c*h*m*j-d*e*o*j+b*h*o*j+c*e*i*j-b*g*i*j-d*g*k*l+c*h*k*l+d*f*o*l-a*h*o*l-c*f*i*l+a*g*i*l+d*e*k*p-b*h*k*p-d*f*m*p+a*h*m*p+b*f*i*p-a*e*i*p-c*e*k*q+b*g*k*q+c*f*m*q-a*g*m*q-b*f*
o*q+a*e*o*q},transpose:function(){var a;a=this.n21;this.n21=this.n12;this.n12=a;a=this.n31;this.n31=this.n13;this.n13=a;a=this.n32;this.n32=this.n23;this.n23=a;a=this.n41;this.n41=this.n14;this.n14=a;a=this.n42;this.n42=this.n24;this.n24=a;a=this.n43;this.n43=this.n34;this.n43=a;return this},clone:function(){var a=new THREE.Matrix4;a.n11=this.n11;a.n12=this.n12;a.n13=this.n13;a.n14=this.n14;a.n21=this.n21;a.n22=this.n22;a.n23=this.n23;a.n24=this.n24;a.n31=this.n31;a.n32=this.n32;a.n33=this.n33;a.n34=
this.n34;a.n41=this.n41;a.n42=this.n42;a.n43=this.n43;a.n44=this.n44;return a},flatten:function(){this.flat[0]=this.n11;this.flat[1]=this.n21;this.flat[2]=this.n31;this.flat[3]=this.n41;this.flat[4]=this.n12;this.flat[5]=this.n22;this.flat[6]=this.n32;this.flat[7]=this.n42;this.flat[8]=this.n13;this.flat[9]=this.n23;this.flat[10]=this.n33;this.flat[11]=this.n43;this.flat[12]=this.n14;this.flat[13]=this.n24;this.flat[14]=this.n34;this.flat[15]=this.n44;return this.flat},flattenToArray:function(a){a[0]=
this.n11;a[1]=this.n21;a[2]=this.n31;a[3]=this.n41;a[4]=this.n12;a[5]=this.n22;a[6]=this.n32;a[7]=this.n42;a[8]=this.n13;a[9]=this.n23;a[10]=this.n33;a[11]=this.n43;a[12]=this.n14;a[13]=this.n24;a[14]=this.n34;a[15]=this.n44;return a},flattenToArrayOffset:function(a,b){a[b]=this.n11;a[b+1]=this.n21;a[b+2]=this.n31;a[b+3]=this.n41;a[b+4]=this.n12;a[b+5]=this.n22;a[b+6]=this.n32;a[b+7]=this.n42;a[b+8]=this.n13;a[b+9]=this.n23;a[b+10]=this.n33;a[b+11]=this.n43;a[b+12]=this.n14;a[b+13]=this.n24;a[b+14]=
this.n34;a[b+15]=this.n44;return a},setTranslation:function(a,b,c){this.set(1,0,0,a,0,1,0,b,0,0,1,c,0,0,0,1);return this},setScale:function(a,b,c){this.set(a,0,0,0,0,b,0,0,0,0,c,0,0,0,0,1);return this},setRotationX:function(a){var b=Math.cos(a),a=Math.sin(a);this.set(1,0,0,0,0,b,-a,0,0,a,b,0,0,0,0,1);return this},setRotationY:function(a){var b=Math.cos(a),a=Math.sin(a);this.set(b,0,a,0,0,1,0,0,-a,0,b,0,0,0,0,1);return this},setRotationZ:function(a){var b=Math.cos(a),a=Math.sin(a);this.set(b,-a,0,
0,a,b,0,0,0,0,1,0,0,0,0,1);return this},setRotationAxis:function(a,b){var c=Math.cos(b),d=Math.sin(b),f=1-c,e=a.x,g=a.y,h=a.z,k=f*e,m=f*g;this.set(k*e+c,k*g-d*h,k*h+d*g,0,k*g+d*h,m*g+c,m*h-d*e,0,k*h-d*g,m*h+d*e,f*h*h+c,0,0,0,0,1);return this},setPosition:function(a){this.n14=a.x;this.n24=a.y;this.n34=a.z;return this},getPosition:function(){if(!this.position)this.position=new THREE.Vector3;this.position.set(this.n14,this.n24,this.n34);return this.position},getColumnX:function(){if(!this.columnX)this.columnX=
new THREE.Vector3;this.columnX.set(this.n11,this.n21,this.n31);return this.columnX},getColumnY:function(){if(!this.columnY)this.columnY=new THREE.Vector3;this.columnY.set(this.n12,this.n22,this.n32);return this.columnY},getColumnZ:function(){if(!this.columnZ)this.columnZ=new THREE.Vector3;this.columnZ.set(this.n13,this.n23,this.n33);return this.columnZ},setRotationFromEuler:function(a,b){var c=a.x,d=a.y,f=a.z,e=Math.cos(c),c=Math.sin(c),g=Math.cos(d),d=Math.sin(d),h=Math.cos(f),f=Math.sin(f);switch(b){case "YXZ":var k=
g*h,m=g*f,o=d*h,i=d*f;this.n11=k+i*c;this.n12=o*c-m;this.n13=e*d;this.n21=e*f;this.n22=e*h;this.n23=-c;this.n31=m*c-o;this.n32=i+k*c;this.n33=e*g;break;case "ZXY":k=g*h;m=g*f;o=d*h;i=d*f;this.n11=k-i*c;this.n12=-e*f;this.n13=o+m*c;this.n21=m+o*c;this.n22=e*h;this.n23=i-k*c;this.n31=-e*d;this.n32=c;this.n33=e*g;break;case "ZYX":k=e*h;m=e*f;o=c*h;i=c*f;this.n11=g*h;this.n12=o*d-m;this.n13=k*d+i;this.n21=g*f;this.n22=i*d+k;this.n23=m*d-o;this.n31=-d;this.n32=c*g;this.n33=e*g;break;case "YZX":k=e*g;m=
e*d;o=c*g;i=c*d;this.n11=g*h;this.n12=i-k*f;this.n13=o*f+m;this.n21=f;this.n22=e*h;this.n23=-c*h;this.n31=-d*h;this.n32=m*f+o;this.n33=k-i*f;break;case "XZY":k=e*g;m=e*d;o=c*g;i=c*d;this.n11=g*h;this.n12=-f;this.n13=d*h;this.n21=k*f+i;this.n22=e*h;this.n23=m*f-o;this.n31=o*f-m;this.n32=c*h;this.n33=i*f+k;break;default:k=e*h,m=e*f,o=c*h,i=c*f,this.n11=g*h,this.n12=-g*f,this.n13=d,this.n21=m+o*d,this.n22=k-i*d,this.n23=-c*g,this.n31=i-k*d,this.n32=o+m*d,this.n33=e*g}return this},setRotationFromQuaternion:function(a){var b=
a.x,c=a.y,d=a.z,f=a.w,e=b+b,g=c+c,h=d+d,a=b*e,k=b*g;b*=h;var m=c*g;c*=h;d*=h;e*=f;g*=f;f*=h;this.n11=1-(m+d);this.n12=k-f;this.n13=b+g;this.n21=k+f;this.n22=1-(a+d);this.n23=c-e;this.n31=b-g;this.n32=c+e;this.n33=1-(a+m);return this},scale:function(a){var b=a.x,c=a.y,a=a.z;this.n11*=b;this.n12*=c;this.n13*=a;this.n21*=b;this.n22*=c;this.n23*=a;this.n31*=b;this.n32*=c;this.n33*=a;this.n41*=b;this.n42*=c;this.n43*=a;return this},compose:function(a,b,c){var d=THREE.Matrix4.__m1,f=THREE.Matrix4.__m2;
d.identity();d.setRotationFromQuaternion(b);f.setScale(c.x,c.y,c.z);this.multiply(d,f);this.n14=a.x;this.n24=a.y;this.n34=a.z;return this},decompose:function(a,b,c){var d=THREE.Matrix4.__v1,f=THREE.Matrix4.__v2,e=THREE.Matrix4.__v3;d.set(this.n11,this.n21,this.n31);f.set(this.n12,this.n22,this.n32);e.set(this.n13,this.n23,this.n33);a=a instanceof THREE.Vector3?a:new THREE.Vector3;b=b instanceof THREE.Quaternion?b:new THREE.Quaternion;c=c instanceof THREE.Vector3?c:new THREE.Vector3;c.x=d.length();
c.y=f.length();c.z=e.length();a.x=this.n14;a.y=this.n24;a.z=this.n34;d=THREE.Matrix4.__m1;d.copy(this);d.n11/=c.x;d.n21/=c.x;d.n31/=c.x;d.n12/=c.y;d.n22/=c.y;d.n32/=c.y;d.n13/=c.z;d.n23/=c.z;d.n33/=c.z;b.setFromRotationMatrix(d);return[a,b,c]},extractPosition:function(a){this.n14=a.n14;this.n24=a.n24;this.n34=a.n34},extractRotation:function(a,b){var c=1/b.x,d=1/b.y,f=1/b.z;this.n11=a.n11*c;this.n21=a.n21*c;this.n31=a.n31*c;this.n12=a.n12*d;this.n22=a.n22*d;this.n32=a.n32*d;this.n13=a.n13*f;this.n23=
a.n23*f;this.n33=a.n33*f}};
THREE.Matrix4.makeInvert=function(a,b){var c=a.n11,d=a.n12,f=a.n13,e=a.n14,g=a.n21,h=a.n22,k=a.n23,m=a.n24,o=a.n31,i=a.n32,j=a.n33,l=a.n34,p=a.n41,q=a.n42,r=a.n43,v=a.n44;b===void 0&&(b=new THREE.Matrix4);b.n11=k*l*q-m*j*q+m*i*r-h*l*r-k*i*v+h*j*v;b.n12=e*j*q-f*l*q-e*i*r+d*l*r+f*i*v-d*j*v;b.n13=f*m*q-e*k*q+e*h*r-d*m*r-f*h*v+d*k*v;b.n14=e*k*i-f*m*i-e*h*j+d*m*j+f*h*l-d*k*l;b.n21=m*j*p-k*l*p-m*o*r+g*l*r+k*o*v-g*j*v;b.n22=f*l*p-e*j*p+e*o*r-c*l*r-f*o*v+c*j*v;b.n23=e*k*p-f*m*p-e*g*r+c*m*r+f*g*v-c*k*v;b.n24=
f*m*o-e*k*o+e*g*j-c*m*j-f*g*l+c*k*l;b.n31=h*l*p-m*i*p+m*o*q-g*l*q-h*o*v+g*i*v;b.n32=e*i*p-d*l*p-e*o*q+c*l*q+d*o*v-c*i*v;b.n33=f*m*p-e*h*p+e*g*q-c*m*q-d*g*v+c*h*v;b.n34=e*h*o-d*m*o-e*g*i+c*m*i+d*g*l-c*h*l;b.n41=k*i*p-h*j*p-k*o*q+g*j*q+h*o*r-g*i*r;b.n42=d*j*p-f*i*p+f*o*q-c*j*q-d*o*r+c*i*r;b.n43=f*h*p-d*k*p-f*g*q+c*k*q+d*g*r-c*h*r;b.n44=d*k*o-f*h*o+f*g*i-c*k*i-d*g*j+c*h*j;b.multiplyScalar(1/a.determinant());return b};
THREE.Matrix4.makeInvert3x3=function(a){var b=a.m33,c=b.m,d=a.n33*a.n22-a.n32*a.n23,f=-a.n33*a.n21+a.n31*a.n23,e=a.n32*a.n21-a.n31*a.n22,g=-a.n33*a.n12+a.n32*a.n13,h=a.n33*a.n11-a.n31*a.n13,k=-a.n32*a.n11+a.n31*a.n12,m=a.n23*a.n12-a.n22*a.n13,o=-a.n23*a.n11+a.n21*a.n13,i=a.n22*a.n11-a.n21*a.n12,a=a.n11*d+a.n21*g+a.n31*m;a==0&&console.error("THREE.Matrix4.makeInvert3x3: Matrix not invertible.");a=1/a;c[0]=a*d;c[1]=a*f;c[2]=a*e;c[3]=a*g;c[4]=a*h;c[5]=a*k;c[6]=a*m;c[7]=a*o;c[8]=a*i;return b};
THREE.Matrix4.makeFrustum=function(a,b,c,d,f,e){var g;g=new THREE.Matrix4;g.n11=2*f/(b-a);g.n12=0;g.n13=(b+a)/(b-a);g.n14=0;g.n21=0;g.n22=2*f/(d-c);g.n23=(d+c)/(d-c);g.n24=0;g.n31=0;g.n32=0;g.n33=-(e+f)/(e-f);g.n34=-2*e*f/(e-f);g.n41=0;g.n42=0;g.n43=-1;g.n44=0;return g};THREE.Matrix4.makePerspective=function(a,b,c,d){var f,a=c*Math.tan(a*Math.PI/360);f=-a;return THREE.Matrix4.makeFrustum(f*b,a*b,f,a,c,d)};
THREE.Matrix4.makeOrtho=function(a,b,c,d,f,e){var g,h,k,m;g=new THREE.Matrix4;h=b-a;k=c-d;m=e-f;g.n11=2/h;g.n12=0;g.n13=0;g.n14=-((b+a)/h);g.n21=0;g.n22=2/k;g.n23=0;g.n24=-((c+d)/k);g.n31=0;g.n32=0;g.n33=-2/m;g.n34=-((e+f)/m);g.n41=0;g.n42=0;g.n43=0;g.n44=1;return g};THREE.Matrix4.__v1=new THREE.Vector3;THREE.Matrix4.__v2=new THREE.Vector3;THREE.Matrix4.__v3=new THREE.Vector3;THREE.Matrix4.__m1=new THREE.Matrix4;THREE.Matrix4.__m2=new THREE.Matrix4;
THREE.Object3D=function(){this.id=THREE.Object3DCount++;this.name="";this.parent=void 0;this.children=[];this.up=new THREE.Vector3(0,1,0);this.position=new THREE.Vector3;this.rotation=new THREE.Vector3;this.eulerOrder="XYZ";this.scale=new THREE.Vector3(1,1,1);this.flipSided=this.doubleSided=this.dynamic=!1;this.renderDepth=null;this.rotationAutoUpdate=!0;this.matrix=new THREE.Matrix4;this.matrixWorld=new THREE.Matrix4;this.matrixRotationWorld=new THREE.Matrix4;this.matrixWorldNeedsUpdate=this.matrixAutoUpdate=
!0;this.quaternion=new THREE.Quaternion;this.useQuaternion=!1;this.boundRadius=0;this.boundRadiusScale=1;this.visible=!0;this.receiveShadow=this.castShadow=!1;this.frustumCulled=!0;this._vector=new THREE.Vector3};
THREE.Object3D.prototype={constructor:THREE.Object3D,translate:function(a,b){this.matrix.rotateAxis(b);this.position.addSelf(b.multiplyScalar(a))},translateX:function(a){this.translate(a,this._vector.set(1,0,0))},translateY:function(a){this.translate(a,this._vector.set(0,1,0))},translateZ:function(a){this.translate(a,this._vector.set(0,0,1))},lookAt:function(a){this.matrix.lookAt(a,this.position,this.up);this.rotationAutoUpdate&&this.rotation.setRotationFromMatrix(this.matrix)},addChild:function(a){if(this.children.indexOf(a)===
-1){a.parent!==void 0&&a.parent.removeChild(a);a.parent=this;this.children.push(a);for(var b=this;b.parent!==void 0;)b=b.parent;b!==void 0&&b instanceof THREE.Scene&&b.addChildRecurse(a)}},removeChild:function(a){var b=this,c=this.children.indexOf(a);if(c!==-1){a.parent=void 0;for(this.children.splice(c,1);b.parent!==void 0;)b=b.parent;b!==void 0&&b instanceof THREE.Scene&&b.removeChildRecurse(a)}},getChildByName:function(a,b){var c,d,f;c=0;for(d=this.children.length;c<d;c++){f=this.children[c];if(f.name===
a)return f;if(b&&(f=f.getChildByName(a,b),f!==void 0))return f}},updateMatrix:function(){this.matrix.setPosition(this.position);this.useQuaternion?this.matrix.setRotationFromQuaternion(this.quaternion):this.matrix.setRotationFromEuler(this.rotation,this.eulerOrder);if(this.scale.x!==1||this.scale.y!==1||this.scale.z!==1)this.matrix.scale(this.scale),this.boundRadiusScale=Math.max(this.scale.x,Math.max(this.scale.y,this.scale.z));this.matrixWorldNeedsUpdate=!0},update:function(a,b,c){this.matrixAutoUpdate&&
this.updateMatrix();if(this.matrixWorldNeedsUpdate||b)a?this.matrixWorld.multiply(a,this.matrix):this.matrixWorld.copy(this.matrix),this.matrixRotationWorld.extractRotation(this.matrixWorld,this.scale),this.matrixWorldNeedsUpdate=!1,b=!0;for(var a=0,d=this.children.length;a<d;a++)this.children[a].update(this.matrixWorld,b,c)}};THREE.Object3DCount=0;
THREE.Projector=function(){function a(){var a=h[g]=h[g]||new THREE.RenderableVertex;g++;return a}function b(a,b){return b.z-a.z}var c,d,f=[],e,g,h=[],k,m,o=[],i,j=[],l,p,q=[],r,v,V=[],x=[],Q=[],y=new THREE.Vector4,C=new THREE.Vector4,n=new THREE.Matrix4,t=new THREE.Matrix4,u=[new THREE.Vector4,new THREE.Vector4,new THREE.Vector4,new THREE.Vector4,new THREE.Vector4,new THREE.Vector4],E=new THREE.Vector4,T=new THREE.Vector4;this.projectVector=function(a,b){n.multiply(b.projectionMatrix,b.matrixWorldInverse);
n.multiplyVector3(a);return a};this.unprojectVector=function(a,b){n.multiply(b.matrixWorld,THREE.Matrix4.makeInvert(b.projectionMatrix));n.multiplyVector3(a);return a};this.projectObjects=function(a,e,g){var h,l;d=x.length=0;h=a.objects;a=0;for(e=h.length;a<e;a++){l=h[a];var k;if(!(k=!l.visible))if(k=l instanceof THREE.Mesh)if(k=l.frustumCulled){a:{k=void 0;for(var i=l.matrixWorld,m=-l.geometry.boundingSphere.radius*Math.max(l.scale.x,Math.max(l.scale.y,l.scale.z)),j=0;j<6;j++)if(k=u[j].x*i.n14+u[j].y*
i.n24+u[j].z*i.n34+u[j].w,k<=m){k=!1;break a}k=!0}k=!k}if(!k)k=f[d]=f[d]||new THREE.RenderableObject,d++,c=k,y.copy(l.position),n.multiplyVector3(y),c.object=l,c.z=y.z,x.push(c)}g&&x.sort(b);return x};this.projectScene=function(c,d,f){var I=d.near,M=d.far,F,J,G,R,w,O,L,y,D,s,B,z,K,x,P,U,Z;v=p=i=m=Q.length=0;d.matrixAutoUpdate&&d.update(void 0,!0);c.update(void 0,!1,d);n.multiply(d.projectionMatrix,d.matrixWorldInverse);u[0].set(n.n41-n.n11,n.n42-n.n12,n.n43-n.n13,n.n44-n.n14);u[1].set(n.n41+n.n11,
n.n42+n.n12,n.n43+n.n13,n.n44+n.n14);u[2].set(n.n41+n.n21,n.n42+n.n22,n.n43+n.n23,n.n44+n.n24);u[3].set(n.n41-n.n21,n.n42-n.n22,n.n43-n.n23,n.n44-n.n24);u[4].set(n.n41-n.n31,n.n42-n.n32,n.n43-n.n33,n.n44-n.n34);u[5].set(n.n41+n.n31,n.n42+n.n32,n.n43+n.n33,n.n44+n.n34);for(F=0;F<6;F++)D=u[F],D.divideScalar(Math.sqrt(D.x*D.x+D.y*D.y+D.z*D.z));D=this.projectObjects(c,d,!0);c=0;for(F=D.length;c<F;c++)if(s=D[c].object,s.visible)if(B=s.matrixWorld,z=s.matrixRotationWorld,K=s.materials,x=s.overdraw,g=0,
s instanceof THREE.Mesh){P=s.geometry;R=P.vertices;U=P.faces;P=P.faceVertexUvs;J=0;for(G=R.length;J<G;J++)e=a(),e.positionWorld.copy(R[J].position),B.multiplyVector3(e.positionWorld),e.positionScreen.copy(e.positionWorld),n.multiplyVector4(e.positionScreen),e.positionScreen.x/=e.positionScreen.w,e.positionScreen.y/=e.positionScreen.w,e.visible=e.positionScreen.z>I&&e.positionScreen.z<M;R=0;for(J=U.length;R<J;R++){G=U[R];if(G instanceof THREE.Face3)if(w=h[G.a],O=h[G.b],L=h[G.c],w.visible&&O.visible&&
L.visible&&(s.doubleSided||s.flipSided!=(L.positionScreen.x-w.positionScreen.x)*(O.positionScreen.y-w.positionScreen.y)-(L.positionScreen.y-w.positionScreen.y)*(O.positionScreen.x-w.positionScreen.x)<0))y=o[m]=o[m]||new THREE.RenderableFace3,m++,k=y,k.v1.copy(w),k.v2.copy(O),k.v3.copy(L);else continue;else if(G instanceof THREE.Face4)if(w=h[G.a],O=h[G.b],L=h[G.c],y=h[G.d],w.visible&&O.visible&&L.visible&&y.visible&&(s.doubleSided||s.flipSided!=((y.positionScreen.x-w.positionScreen.x)*(O.positionScreen.y-
w.positionScreen.y)-(y.positionScreen.y-w.positionScreen.y)*(O.positionScreen.x-w.positionScreen.x)<0||(O.positionScreen.x-L.positionScreen.x)*(y.positionScreen.y-L.positionScreen.y)-(O.positionScreen.y-L.positionScreen.y)*(y.positionScreen.x-L.positionScreen.x)<0)))Z=j[i]=j[i]||new THREE.RenderableFace4,i++,k=Z,k.v1.copy(w),k.v2.copy(O),k.v3.copy(L),k.v4.copy(y);else continue;k.normalWorld.copy(G.normal);z.multiplyVector3(k.normalWorld);k.centroidWorld.copy(G.centroid);B.multiplyVector3(k.centroidWorld);
k.centroidScreen.copy(k.centroidWorld);n.multiplyVector3(k.centroidScreen);L=G.vertexNormals;w=0;for(O=L.length;w<O;w++)y=k.vertexNormalsWorld[w],y.copy(L[w]),z.multiplyVector3(y);w=0;for(O=P.length;w<O;w++)if(Z=P[w][R]){L=0;for(y=Z.length;L<y;L++)k.uvs[w][L]=Z[L]}k.meshMaterials=K;k.faceMaterials=G.materials;k.overdraw=x;k.z=k.centroidScreen.z;Q.push(k)}}else if(s instanceof THREE.Line){t.multiply(n,B);R=s.geometry.vertices;w=a();w.positionScreen.copy(R[0].position);t.multiplyVector4(w.positionScreen);
J=1;for(G=R.length;J<G;J++){w=a();w.positionScreen.copy(R[J].position);t.multiplyVector4(w.positionScreen);O=h[g-2];E.copy(w.positionScreen);T.copy(O.positionScreen);z=E;K=T;x=0;P=1;U=z.z+z.w;var W=K.z+K.w,fa=-z.z+z.w,ga=-K.z+K.w;if(U>=0&&W>=0&&fa>=0&&ga>=0||(U<0&&W<0||fa<0&&ga<0?0:(U<0?x=Math.max(x,U/(U-W)):W<0&&(P=Math.min(P,U/(U-W))),fa<0?x=Math.max(x,fa/(fa-ga)):ga<0&&(P=Math.min(P,fa/(fa-ga))),P<x?!1:(z.lerpSelf(K,x),K.lerpSelf(z,1-P),!0))))E.multiplyScalar(1/E.w),T.multiplyScalar(1/T.w),B=q[p]=
q[p]||new THREE.RenderableLine,p++,l=B,l.v1.positionScreen.copy(E),l.v2.positionScreen.copy(T),l.z=Math.max(E.z,T.z),l.materials=s.materials,Q.push(l)}}else if(s instanceof THREE.Particle&&(C.set(s.matrixWorld.n14,s.matrixWorld.n24,s.matrixWorld.n34,1),n.multiplyVector4(C),C.z/=C.w,C.z>0&&C.z<1))B=V[v]=V[v]||new THREE.RenderableParticle,v++,r=B,r.x=C.x/C.w,r.y=C.y/C.w,r.z=C.z,r.rotation=s.rotation.z,r.scale.x=s.scale.x*Math.abs(r.x-(C.x+d.projectionMatrix.n11)/(C.w+d.projectionMatrix.n14)),r.scale.y=
s.scale.y*Math.abs(r.y-(C.y+d.projectionMatrix.n22)/(C.w+d.projectionMatrix.n24)),r.materials=s.materials,Q.push(r);f&&Q.sort(b);return Q}};THREE.Quaternion=function(a,b,c,d){this.set(a||0,b||0,c||0,d!==void 0?d:1)};
THREE.Quaternion.prototype={constructor:THREE.Quaternion,set:function(a,b,c,d){this.x=a;this.y=b;this.z=c;this.w=d;return this},copy:function(a){this.x=a.x;this.y=a.y;this.z=a.z;this.w=a.w;return this},setFromEuler:function(a){var b=0.5*Math.PI/360,c=a.x*b,d=a.y*b,f=a.z*b,a=Math.cos(d),d=Math.sin(d),b=Math.cos(-f),f=Math.sin(-f),e=Math.cos(c),c=Math.sin(c),g=a*b,h=d*f;this.w=g*e-h*c;this.x=g*c+h*e;this.y=d*b*e+a*f*c;this.z=a*f*e-d*b*c;return this},setFromAxisAngle:function(a,b){var c=b/2,d=Math.sin(c);
this.x=a.x*d;this.y=a.y*d;this.z=a.z*d;this.w=Math.cos(c);return this},setFromRotationMatrix:function(a){var b=Math.pow(a.determinant(),1/3);this.w=Math.sqrt(Math.max(0,b+a.n11+a.n22+a.n33))/2;this.x=Math.sqrt(Math.max(0,b+a.n11-a.n22-a.n33))/2;this.y=Math.sqrt(Math.max(0,b-a.n11+a.n22-a.n33))/2;this.z=Math.sqrt(Math.max(0,b-a.n11-a.n22+a.n33))/2;this.x=a.n32-a.n23<0?-Math.abs(this.x):Math.abs(this.x);this.y=a.n13-a.n31<0?-Math.abs(this.y):Math.abs(this.y);this.z=a.n21-a.n12<0?-Math.abs(this.z):Math.abs(this.z);
this.normalize();return this},calculateW:function(){this.w=-Math.sqrt(Math.abs(1-this.x*this.x-this.y*this.y-this.z*this.z));return this},inverse:function(){this.x*=-1;this.y*=-1;this.z*=-1;return this},length:function(){return Math.sqrt(this.x*this.x+this.y*this.y+this.z*this.z+this.w*this.w)},normalize:function(){var a=Math.sqrt(this.x*this.x+this.y*this.y+this.z*this.z+this.w*this.w);a==0?this.w=this.z=this.y=this.x=0:(a=1/a,this.x*=a,this.y*=a,this.z*=a,this.w*=a);return this},multiplySelf:function(a){var b=
this.x,c=this.y,d=this.z,f=this.w,e=a.x,g=a.y,h=a.z,a=a.w;this.x=b*a+f*e+c*h-d*g;this.y=c*a+f*g+d*e-b*h;this.z=d*a+f*h+b*g-c*e;this.w=f*a-b*e-c*g-d*h;return this},multiply:function(a,b){this.x=a.x*b.w+a.y*b.z-a.z*b.y+a.w*b.x;this.y=-a.x*b.z+a.y*b.w+a.z*b.x+a.w*b.y;this.z=a.x*b.y-a.y*b.x+a.z*b.w+a.w*b.z;this.w=-a.x*b.x-a.y*b.y-a.z*b.z+a.w*b.w;return this},multiplyVector3:function(a,b){b||(b=a);var c=a.x,d=a.y,f=a.z,e=this.x,g=this.y,h=this.z,k=this.w,m=k*c+g*f-h*d,o=k*d+h*c-e*f,i=k*f+e*d-g*c,c=-e*
c-g*d-h*f;b.x=m*k+c*-e+o*-h-i*-g;b.y=o*k+c*-g+i*-e-m*-h;b.z=i*k+c*-h+m*-g-o*-e;return b}};THREE.Quaternion.slerp=function(a,b,c,d){var f=a.w*b.w+a.x*b.x+a.y*b.y+a.z*b.z;if(Math.abs(f)>=1)return c.w=a.w,c.x=a.x,c.y=a.y,c.z=a.z,c;var e=Math.acos(f),g=Math.sqrt(1-f*f);if(Math.abs(g)<0.001)return c.w=0.5*(a.w+b.w),c.x=0.5*(a.x+b.x),c.y=0.5*(a.y+b.y),c.z=0.5*(a.z+b.z),c;f=Math.sin((1-d)*e)/g;d=Math.sin(d*e)/g;c.w=a.w*f+b.w*d;c.x=a.x*f+b.x*d;c.y=a.y*f+b.y*d;c.z=a.z*f+b.z*d;return c};
THREE.Vertex=function(a){this.position=a||new THREE.Vector3};THREE.Face3=function(a,b,c,d,f,e){this.a=a;this.b=b;this.c=c;this.normal=d instanceof THREE.Vector3?d:new THREE.Vector3;this.vertexNormals=d instanceof Array?d:[];this.color=f instanceof THREE.Color?f:new THREE.Color;this.vertexColors=f instanceof Array?f:[];this.vertexTangents=[];this.materials=e instanceof Array?e:[e];this.centroid=new THREE.Vector3};
THREE.Face4=function(a,b,c,d,f,e,g){this.a=a;this.b=b;this.c=c;this.d=d;this.normal=f instanceof THREE.Vector3?f:new THREE.Vector3;this.vertexNormals=f instanceof Array?f:[];this.color=e instanceof THREE.Color?e:new THREE.Color;this.vertexColors=e instanceof Array?e:[];this.vertexTangents=[];this.materials=g instanceof Array?g:[g];this.centroid=new THREE.Vector3};THREE.UV=function(a,b){this.u=a||0;this.v=b||0};
THREE.UV.prototype={constructor:THREE.UV,set:function(a,b){this.u=a;this.v=b;return this},copy:function(a){this.u=a.u;this.v=a.v;return this},clone:function(){return new THREE.UV(this.u,this.v)}};
THREE.Geometry=function(){this.id=THREE.GeometryCount++;this.vertices=[];this.colors=[];this.faces=[];this.edges=[];this.faceUvs=[[]];this.faceVertexUvs=[[]];this.morphTargets=[];this.morphColors=[];this.skinWeights=[];this.skinIndices=[];this.boundingSphere=this.boundingBox=null;this.dynamic=this.hasTangents=!1};
THREE.Geometry.prototype={constructor:THREE.Geometry,computeCentroids:function(){var a,b,c;a=0;for(b=this.faces.length;a<b;a++)c=this.faces[a],c.centroid.set(0,0,0),c instanceof THREE.Face3?(c.centroid.addSelf(this.vertices[c.a].position),c.centroid.addSelf(this.vertices[c.b].position),c.centroid.addSelf(this.vertices[c.c].position),c.centroid.divideScalar(3)):c instanceof THREE.Face4&&(c.centroid.addSelf(this.vertices[c.a].position),c.centroid.addSelf(this.vertices[c.b].position),c.centroid.addSelf(this.vertices[c.c].position),
c.centroid.addSelf(this.vertices[c.d].position),c.centroid.divideScalar(4))},computeFaceNormals:function(a){var b,c,d,f,e,g,h=new THREE.Vector3,k=new THREE.Vector3;d=0;for(f=this.faces.length;d<f;d++){e=this.faces[d];if(a&&e.vertexNormals.length){h.set(0,0,0);b=0;for(c=e.vertexNormals.length;b<c;b++)h.addSelf(e.vertexNormals[b]);h.divideScalar(3)}else b=this.vertices[e.a],c=this.vertices[e.b],g=this.vertices[e.c],h.sub(g.position,c.position),k.sub(b.position,c.position),h.crossSelf(k);h.isZero()||
h.normalize();e.normal.copy(h)}},computeVertexNormals:function(){var a,b,c,d;if(this.__tmpVertices==void 0){d=this.__tmpVertices=Array(this.vertices.length);a=0;for(b=this.vertices.length;a<b;a++)d[a]=new THREE.Vector3;a=0;for(b=this.faces.length;a<b;a++)if(c=this.faces[a],c instanceof THREE.Face3)c.vertexNormals=[new THREE.Vector3,new THREE.Vector3,new THREE.Vector3];else if(c instanceof THREE.Face4)c.vertexNormals=[new THREE.Vector3,new THREE.Vector3,new THREE.Vector3,new THREE.Vector3]}else{d=
this.__tmpVertices;a=0;for(b=this.vertices.length;a<b;a++)d[a].set(0,0,0)}a=0;for(b=this.faces.length;a<b;a++)c=this.faces[a],c instanceof THREE.Face3?(d[c.a].addSelf(c.normal),d[c.b].addSelf(c.normal),d[c.c].addSelf(c.normal)):c instanceof THREE.Face4&&(d[c.a].addSelf(c.normal),d[c.b].addSelf(c.normal),d[c.c].addSelf(c.normal),d[c.d].addSelf(c.normal));a=0;for(b=this.vertices.length;a<b;a++)d[a].normalize();a=0;for(b=this.faces.length;a<b;a++)c=this.faces[a],c instanceof THREE.Face3?(c.vertexNormals[0].copy(d[c.a]),
c.vertexNormals[1].copy(d[c.b]),c.vertexNormals[2].copy(d[c.c])):c instanceof THREE.Face4&&(c.vertexNormals[0].copy(d[c.a]),c.vertexNormals[1].copy(d[c.b]),c.vertexNormals[2].copy(d[c.c]),c.vertexNormals[3].copy(d[c.d]))},computeTangents:function(){function a(a,b,c,d,e,f,t){h=a.vertices[b].position;k=a.vertices[c].position;m=a.vertices[d].position;o=g[e];i=g[f];j=g[t];l=k.x-h.x;p=m.x-h.x;q=k.y-h.y;r=m.y-h.y;v=k.z-h.z;V=m.z-h.z;x=i.u-o.u;Q=j.u-o.u;y=i.v-o.v;C=j.v-o.v;n=1/(x*C-Q*y);T.set((C*l-y*p)*
n,(C*q-y*r)*n,(C*v-y*V)*n);ba.set((x*p-Q*l)*n,(x*r-Q*q)*n,(x*V-Q*v)*n);u[b].addSelf(T);u[c].addSelf(T);u[d].addSelf(T);E[b].addSelf(ba);E[c].addSelf(ba);E[d].addSelf(ba)}var b,c,d,f,e,g,h,k,m,o,i,j,l,p,q,r,v,V,x,Q,y,C,n,t,u=[],E=[],T=new THREE.Vector3,ba=new THREE.Vector3,H=new THREE.Vector3,N=new THREE.Vector3,I=new THREE.Vector3;b=0;for(c=this.vertices.length;b<c;b++)u[b]=new THREE.Vector3,E[b]=new THREE.Vector3;b=0;for(c=this.faces.length;b<c;b++)e=this.faces[b],g=this.faceVertexUvs[0][b],e instanceof
THREE.Face3?a(this,e.a,e.b,e.c,0,1,2):e instanceof THREE.Face4&&(a(this,e.a,e.b,e.c,0,1,2),a(this,e.a,e.b,e.d,0,1,3));var M=["a","b","c","d"];b=0;for(c=this.faces.length;b<c;b++){e=this.faces[b];for(d=0;d<e.vertexNormals.length;d++)I.copy(e.vertexNormals[d]),f=e[M[d]],t=u[f],H.copy(t),H.subSelf(I.multiplyScalar(I.dot(t))).normalize(),N.cross(e.vertexNormals[d],t),f=N.dot(E[f]),f=f<0?-1:1,e.vertexTangents[d]=new THREE.Vector4(H.x,H.y,H.z,f)}this.hasTangents=!0},computeBoundingBox:function(){var a;
if(this.vertices.length>0){this.boundingBox={x:[this.vertices[0].position.x,this.vertices[0].position.x],y:[this.vertices[0].position.y,this.vertices[0].position.y],z:[this.vertices[0].position.z,this.vertices[0].position.z]};for(var b=1,c=this.vertices.length;b<c;b++){a=this.vertices[b];if(a.position.x<this.boundingBox.x[0])this.boundingBox.x[0]=a.position.x;else if(a.position.x>this.boundingBox.x[1])this.boundingBox.x[1]=a.position.x;if(a.position.y<this.boundingBox.y[0])this.boundingBox.y[0]=a.position.y;
else if(a.position.y>this.boundingBox.y[1])this.boundingBox.y[1]=a.position.y;if(a.position.z<this.boundingBox.z[0])this.boundingBox.z[0]=a.position.z;else if(a.position.z>this.boundingBox.z[1])this.boundingBox.z[1]=a.position.z}}},computeBoundingSphere:function(){for(var a=0,b=0,c=this.vertices.length;b<c;b++)a=Math.max(a,this.vertices[b].position.length());this.boundingSphere={radius:a}},computeEdgeFaces:function(){function a(a,b){return Math.min(a,b)+"_"+Math.max(a,b)}function b(a,b,c){a[b]===
void 0?(a[b]={set:{},array:[]},a[b].set[c]=1,a[b].array.push(c)):a[b].set[c]===void 0&&(a[b].set[c]=1,a[b].array.push(c))}var c,d,f,e,g,h={};c=0;for(d=this.faces.length;c<d;c++)g=this.faces[c],g instanceof THREE.Face3?(f=a(g.a,g.b),b(h,f,c),f=a(g.b,g.c),b(h,f,c),f=a(g.a,g.c),b(h,f,c)):g instanceof THREE.Face4&&(f=a(g.b,g.d),b(h,f,c),f=a(g.a,g.b),b(h,f,c),f=a(g.a,g.d),b(h,f,c),f=a(g.b,g.c),b(h,f,c),f=a(g.c,g.d),b(h,f,c));c=0;for(d=this.edges.length;c<d;c++){g=this.edges[c];f=g.vertexIndices[0];e=g.vertexIndices[1];
g.faceIndices=h[a(f,e)].array;for(f=0;f<g.faceIndices.length;f++)e=g.faceIndices[f],g.faces.push(this.faces[e])}}};THREE.GeometryCount=0;THREE.Camera=function(a,b,c,d,f){THREE.Object3D.call(this);this.fov=a||50;this.aspect=b||1;this.near=c||0.1;this.far=d||2E3;this.target=f||new THREE.Object3D;this.useTarget=!0;this.matrixWorldInverse=new THREE.Matrix4;this.projectionMatrix=null;this.updateProjectionMatrix()};THREE.Camera.prototype=new THREE.Object3D;THREE.Camera.prototype.constructor=THREE.Camera;
THREE.Camera.prototype.supr=THREE.Object3D.prototype;THREE.Camera.prototype.translate=function(a,b){this.matrix.rotateAxis(b);b.multiplyScalar(a);this.position.addSelf(b);this.target.position.addSelf(b)};
THREE.Camera.prototype.updateProjectionMatrix=function(){if(this.fullWidth){var a=this.fullWidth/this.fullHeight,b=Math.tan(this.fov*Math.PI/360)*this.near,c=-b,d=a*c,a=Math.abs(a*b-d),c=Math.abs(b-c);this.projectionMatrix=THREE.Matrix4.makeFrustum(d+this.x*a/this.fullWidth,d+(this.x+this.width)*a/this.fullWidth,b-(this.y+this.height)*c/this.fullHeight,b-this.y*c/this.fullHeight,this.near,this.far)}else this.projectionMatrix=THREE.Matrix4.makePerspective(this.fov,this.aspect,this.near,this.far)};
THREE.Camera.prototype.setViewOffset=function(a,b,c,d,f,e){this.fullWidth=a;this.fullHeight=b;this.x=c;this.y=d;this.width=f;this.height=e;this.updateProjectionMatrix()};
THREE.Camera.prototype.update=function(a,b,c){if(this.useTarget)this.matrix.lookAt(this.position,this.target.position,this.up),this.matrix.setPosition(this.position),a?this.matrixWorld.multiply(a,this.matrix):this.matrixWorld.copy(this.matrix),THREE.Matrix4.makeInvert(this.matrixWorld,this.matrixWorldInverse),b=!0;else if(this.matrixAutoUpdate&&this.updateMatrix(),b||this.matrixWorldNeedsUpdate)a?this.matrixWorld.multiply(a,this.matrix):this.matrixWorld.copy(this.matrix),this.matrixWorldNeedsUpdate=
!1,b=!0,THREE.Matrix4.makeInvert(this.matrixWorld,this.matrixWorldInverse);for(a=0;a<this.children.length;a++)this.children[a].update(this.matrixWorld,b,c)};THREE.OrthoCamera=function(a,b,c,d,f,e,g){THREE.Camera.call(this,45,1,f,e,g);this.left=a;this.right=b;this.top=c;this.bottom=d;this.updateProjectionMatrix()};THREE.OrthoCamera.prototype=new THREE.Camera;THREE.OrthoCamera.prototype.constructor=THREE.OrthoCamera;
THREE.OrthoCamera.prototype.updateProjectionMatrix=function(){this.projectionMatrix=THREE.Matrix4.makeOrtho(this.left,this.right,this.top,this.bottom,this.near,this.far)};THREE.Light=function(a){THREE.Object3D.call(this);this.color=new THREE.Color(a)};THREE.Light.prototype=new THREE.Object3D;THREE.Light.prototype.constructor=THREE.Light;THREE.Light.prototype.supr=THREE.Object3D.prototype;THREE.AmbientLight=function(a){THREE.Light.call(this,a)};THREE.AmbientLight.prototype=new THREE.Light;
THREE.AmbientLight.prototype.constructor=THREE.AmbientLight;THREE.DirectionalLight=function(a,b,c,d){THREE.Light.call(this,a);this.position=new THREE.Vector3(0,1,0);this.intensity=b||1;this.distance=c||0;this.castShadow=d!==void 0?d:!1};THREE.DirectionalLight.prototype=new THREE.Light;THREE.DirectionalLight.prototype.constructor=THREE.DirectionalLight;THREE.PointLight=function(a,b,c){THREE.Light.call(this,a);this.position=new THREE.Vector3;this.intensity=b||1;this.distance=c||0};
THREE.PointLight.prototype=new THREE.Light;THREE.PointLight.prototype.constructor=THREE.PointLight;
THREE.Material=function(a){this.id=THREE.MaterialCount++;a=a||{};this.opacity=a.opacity!==void 0?a.opacity:1;this.transparent=a.transparent!==void 0?a.transparent:!1;this.blending=a.blending!==void 0?a.blending:THREE.NormalBlending;this.depthTest=a.depthTest!==void 0?a.depthTest:!0;this.polygonOffset=a.polygonOffset!==void 0?a.polygonOffset:!1;this.polygonOffsetFactor=a.polygonOffsetFactor!==void 0?a.polygonOffsetFactor:0;this.polygonOffsetUnits=a.polygonOffsetUnits!==void 0?a.polygonOffsetUnits:
0;this.alphaTest=a.alphaTest!==void 0?a.alphaTest:0};THREE.MaterialCount=0;THREE.NoShading=0;THREE.FlatShading=1;THREE.SmoothShading=2;THREE.NoColors=0;THREE.FaceColors=1;THREE.VertexColors=2;THREE.NormalBlending=0;THREE.AdditiveBlending=1;THREE.SubtractiveBlending=2;THREE.MultiplyBlending=3;THREE.AdditiveAlphaBlending=4;
THREE.LineBasicMaterial=function(a){THREE.Material.call(this,a);a=a||{};this.color=a.color!==void 0?new THREE.Color(a.color):new THREE.Color(16777215);this.linewidth=a.linewidth!==void 0?a.linewidth:1;this.linecap=a.linecap!==void 0?a.linecap:"round";this.linejoin=a.linejoin!==void 0?a.linejoin:"round";this.vertexColors=a.vertexColors?a.vertexColors:!1};THREE.LineBasicMaterial.prototype=new THREE.Material;THREE.LineBasicMaterial.prototype.constructor=THREE.LineBasicMaterial;
THREE.MeshBasicMaterial=function(a){THREE.Material.call(this,a);a=a||{};this.color=a.color!==void 0?new THREE.Color(a.color):new THREE.Color(16777215);this.map=a.map!==void 0?a.map:null;this.lightMap=a.lightMap!==void 0?a.lightMap:null;this.envMap=a.envMap!==void 0?a.envMap:null;this.combine=a.combine!==void 0?a.combine:THREE.MultiplyOperation;this.reflectivity=a.reflectivity!==void 0?a.reflectivity:1;this.refractionRatio=a.refractionRatio!==void 0?a.refractionRatio:0.98;this.shading=a.shading!==
void 0?a.shading:THREE.SmoothShading;this.wireframe=a.wireframe!==void 0?a.wireframe:!1;this.wireframeLinewidth=a.wireframeLinewidth!==void 0?a.wireframeLinewidth:1;this.wireframeLinecap=a.wireframeLinecap!==void 0?a.wireframeLinecap:"round";this.wireframeLinejoin=a.wireframeLinejoin!==void 0?a.wireframeLinejoin:"round";this.vertexColors=a.vertexColors!==void 0?a.vertexColors:!1;this.skinning=a.skinning!==void 0?a.skinning:!1;this.morphTargets=a.morphTargets!==void 0?a.morphTargets:!1};
THREE.MeshBasicMaterial.prototype=new THREE.Material;THREE.MeshBasicMaterial.prototype.constructor=THREE.MeshBasicMaterial;
THREE.MeshLambertMaterial=function(a){THREE.Material.call(this,a);a=a||{};this.color=a.color!==void 0?new THREE.Color(a.color):new THREE.Color(16777215);this.map=a.map!==void 0?a.map:null;this.lightMap=a.lightMap!==void 0?a.lightMap:null;this.envMap=a.envMap!==void 0?a.envMap:null;this.combine=a.combine!==void 0?a.combine:THREE.MultiplyOperation;this.reflectivity=a.reflectivity!==void 0?a.reflectivity:1;this.refractionRatio=a.refractionRatio!==void 0?a.refractionRatio:0.98;this.shading=a.shading!==
void 0?a.shading:THREE.SmoothShading;this.wireframe=a.wireframe!==void 0?a.wireframe:!1;this.wireframeLinewidth=a.wireframeLinewidth!==void 0?a.wireframeLinewidth:1;this.wireframeLinecap=a.wireframeLinecap!==void 0?a.wireframeLinecap:"round";this.wireframeLinejoin=a.wireframeLinejoin!==void 0?a.wireframeLinejoin:"round";this.vertexColors=a.vertexColors!==void 0?a.vertexColors:!1;this.skinning=a.skinning!==void 0?a.skinning:!1;this.morphTargets=a.morphTargets!==void 0?a.morphTargets:!1};
THREE.MeshLambertMaterial.prototype=new THREE.Material;THREE.MeshLambertMaterial.prototype.constructor=THREE.MeshLambertMaterial;
THREE.MeshPhongMaterial=function(a){THREE.Material.call(this,a);a=a||{};this.color=a.color!==void 0?new THREE.Color(a.color):new THREE.Color(16777215);this.ambient=a.ambient!==void 0?new THREE.Color(a.ambient):new THREE.Color(328965);this.specular=a.specular!==void 0?new THREE.Color(a.specular):new THREE.Color(1118481);this.shininess=a.shininess!==void 0?a.shininess:30;this.map=a.map!==void 0?a.map:null;this.lightMap=a.lightMap!==void 0?a.lightMap:null;this.envMap=a.envMap!==void 0?a.envMap:null;
this.combine=a.combine!==void 0?a.combine:THREE.MultiplyOperation;this.reflectivity=a.reflectivity!==void 0?a.reflectivity:1;this.refractionRatio=a.refractionRatio!==void 0?a.refractionRatio:0.98;this.shading=a.shading!==void 0?a.shading:THREE.SmoothShading;this.wireframe=a.wireframe!==void 0?a.wireframe:!1;this.wireframeLinewidth=a.wireframeLinewidth!==void 0?a.wireframeLinewidth:1;this.wireframeLinecap=a.wireframeLinecap!==void 0?a.wireframeLinecap:"round";this.wireframeLinejoin=a.wireframeLinejoin!==
void 0?a.wireframeLinejoin:"round";this.vertexColors=a.vertexColors!==void 0?a.vertexColors:!1;this.skinning=a.skinning!==void 0?a.skinning:!1;this.morphTargets=a.morphTargets!==void 0?a.morphTargets:!1};THREE.MeshPhongMaterial.prototype=new THREE.Material;THREE.MeshPhongMaterial.prototype.constructor=THREE.MeshPhongMaterial;
THREE.MeshDepthMaterial=function(a){THREE.Material.call(this,a);a=a||{};this.shading=a.shading!==void 0?a.shading:THREE.SmoothShading;this.wireframe=a.wireframe!==void 0?a.wireframe:!1;this.wireframeLinewidth=a.wireframeLinewidth!==void 0?a.wireframeLinewidth:1};THREE.MeshDepthMaterial.prototype=new THREE.Material;THREE.MeshDepthMaterial.prototype.constructor=THREE.MeshDepthMaterial;
THREE.MeshNormalMaterial=function(a){THREE.Material.call(this,a);a=a||{};this.shading=a.shading?a.shading:THREE.FlatShading;this.wireframe=a.wireframe?a.wireframe:!1;this.wireframeLinewidth=a.wireframeLinewidth?a.wireframeLinewidth:1};THREE.MeshNormalMaterial.prototype=new THREE.Material;THREE.MeshNormalMaterial.prototype.constructor=THREE.MeshNormalMaterial;THREE.MeshFaceMaterial=function(){};
THREE.ParticleBasicMaterial=function(a){THREE.Material.call(this,a);a=a||{};this.color=a.color!==void 0?new THREE.Color(a.color):new THREE.Color(16777215);this.map=a.map!==void 0?a.map:null;this.size=a.size!==void 0?a.size:1;this.sizeAttenuation=a.sizeAttenuation!==void 0?a.sizeAttenuation:!0;this.vertexColors=a.vertexColors!==void 0?a.vertexColors:!1};THREE.ParticleBasicMaterial.prototype=new THREE.Material;THREE.ParticleBasicMaterial.prototype.constructor=THREE.ParticleBasicMaterial;
THREE.ParticleCanvasMaterial=function(a){THREE.Material.call(this,a);a=a||{};this.color=a.color!==void 0?new THREE.Color(a.color):new THREE.Color(16777215);this.program=a.program!==void 0?a.program:function(){}};THREE.ParticleCanvasMaterial.prototype=new THREE.Material;THREE.ParticleCanvasMaterial.prototype.constructor=THREE.ParticleCanvasMaterial;
THREE.Texture=function(a,b,c,d,f,e){this.id=THREE.TextureCount++;this.image=a;this.mapping=b!==void 0?b:new THREE.UVMapping;this.wrapS=c!==void 0?c:THREE.ClampToEdgeWrapping;this.wrapT=d!==void 0?d:THREE.ClampToEdgeWrapping;this.magFilter=f!==void 0?f:THREE.LinearFilter;this.minFilter=e!==void 0?e:THREE.LinearMipMapLinearFilter;this.offset=new THREE.Vector2(0,0);this.repeat=new THREE.Vector2(1,1);this.needsUpdate=!1};
THREE.Texture.prototype={constructor:THREE.Texture,clone:function(){var a=new THREE.Texture(this.image,this.mapping,this.wrapS,this.wrapT,this.magFilter,this.minFilter);a.offset.copy(this.offset);a.repeat.copy(this.repeat);return a}};THREE.TextureCount=0;THREE.MultiplyOperation=0;THREE.MixOperation=1;THREE.CubeReflectionMapping=function(){};THREE.CubeRefractionMapping=function(){};THREE.LatitudeReflectionMapping=function(){};THREE.LatitudeRefractionMapping=function(){};
THREE.SphericalReflectionMapping=function(){};THREE.SphericalRefractionMapping=function(){};THREE.UVMapping=function(){};THREE.RepeatWrapping=0;THREE.ClampToEdgeWrapping=1;THREE.MirroredRepeatWrapping=2;THREE.NearestFilter=3;THREE.NearestMipMapNearestFilter=4;THREE.NearestMipMapLinearFilter=5;THREE.LinearFilter=6;THREE.LinearMipMapNearestFilter=7;THREE.LinearMipMapLinearFilter=8;THREE.ByteType=9;THREE.UnsignedByteType=10;THREE.ShortType=11;THREE.UnsignedShortType=12;THREE.IntType=13;
THREE.UnsignedIntType=14;THREE.FloatType=15;THREE.AlphaFormat=16;THREE.RGBFormat=17;THREE.RGBAFormat=18;THREE.LuminanceFormat=19;THREE.LuminanceAlphaFormat=20;THREE.Particle=function(a){THREE.Object3D.call(this);this.materials=a instanceof Array?a:[a]};THREE.Particle.prototype=new THREE.Object3D;THREE.Particle.prototype.constructor=THREE.Particle;THREE.Line=function(a,b,c){THREE.Object3D.call(this);this.geometry=a;this.materials=b instanceof Array?b:[b];this.type=c!=void 0?c:THREE.LineStrip};
THREE.LineStrip=0;THREE.LinePieces=1;THREE.Line.prototype=new THREE.Object3D;THREE.Line.prototype.constructor=THREE.Line;
THREE.Mesh=function(a,b){THREE.Object3D.call(this);this.geometry=a;this.materials=b&&b.length?b:[b];this.overdraw=!1;if(this.geometry&&(this.geometry.boundingSphere||this.geometry.computeBoundingSphere(),this.boundRadius=a.boundingSphere.radius,this.geometry.morphTargets.length)){this.morphTargetBase=-1;this.morphTargetForcedOrder=[];this.morphTargetInfluences=[];this.morphTargetDictionary={};for(var c=0;c<this.geometry.morphTargets.length;c++)this.morphTargetInfluences.push(0),this.morphTargetDictionary[this.geometry.morphTargets[c].name]=
c}};THREE.Mesh.prototype=new THREE.Object3D;THREE.Mesh.prototype.constructor=THREE.Mesh;THREE.Mesh.prototype.supr=THREE.Object3D.prototype;THREE.Mesh.prototype.getMorphTargetIndexByName=function(a){if(this.morphTargetDictionary[a]!==void 0)return this.morphTargetDictionary[a];console.log("THREE.Mesh.getMorphTargetIndexByName: morph target "+a+" does not exist. Returning 0.");return 0};
THREE.Bone=function(a){THREE.Object3D.call(this);this.skin=a;this.skinMatrix=new THREE.Matrix4;this.hasNoneBoneChildren=!1};THREE.Bone.prototype=new THREE.Object3D;THREE.Bone.prototype.constructor=THREE.Bone;THREE.Bone.prototype.supr=THREE.Object3D.prototype;
THREE.Bone.prototype.update=function(a,b,c){this.matrixAutoUpdate&&(b|=this.updateMatrix());if(b||this.matrixWorldNeedsUpdate)a?this.skinMatrix.multiply(a,this.matrix):this.skinMatrix.copy(this.matrix),this.matrixWorldNeedsUpdate=!1,b=!0;var d,f=this.children.length;if(this.hasNoneBoneChildren){this.matrixWorld.multiply(this.skin.matrixWorld,this.skinMatrix);for(d=0;d<f;d++)a=this.children[d],a instanceof THREE.Bone?a.update(this.skinMatrix,b,c):a.update(this.matrixWorld,!0,c)}else for(d=0;d<f;d++)this.children[d].update(this.skinMatrix,
b,c)};THREE.Bone.prototype.addChild=function(a){if(this.children.indexOf(a)===-1&&(a.parent!==void 0&&a.parent.removeChild(a),a.parent=this,this.children.push(a),!(a instanceof THREE.Bone)))this.hasNoneBoneChildren=!0};THREE.Scene=function(){THREE.Object3D.call(this);this.matrixAutoUpdate=!1;this.collisions=this.overrideMaterial=this.fog=null;this.objects=[];this.lights=[];this.__objectsAdded=[];this.__objectsRemoved=[]};THREE.Scene.prototype=new THREE.Object3D;THREE.Scene.prototype.constructor=THREE.Scene;
THREE.Scene.prototype.supr=THREE.Object3D.prototype;THREE.Scene.prototype.addChild=function(a){this.supr.addChild.call(this,a);this.addChildRecurse(a)};THREE.Scene.prototype.addChildRecurse=function(a){if(a instanceof THREE.Light)this.lights.indexOf(a)===-1&&this.lights.push(a);else if(!(a instanceof THREE.Camera||a instanceof THREE.Bone)&&this.objects.indexOf(a)===-1)this.objects.push(a),this.__objectsAdded.push(a);for(var b=0;b<a.children.length;b++)this.addChildRecurse(a.children[b])};
THREE.Scene.prototype.removeChild=function(a){this.supr.removeChild.call(this,a);this.removeChildRecurse(a)};THREE.Scene.prototype.removeChildRecurse=function(a){if(a instanceof THREE.Light){var b=this.lights.indexOf(a);b!==-1&&this.lights.splice(b,1)}else a instanceof THREE.Camera||(b=this.objects.indexOf(a),b!==-1&&(this.objects.splice(b,1),this.__objectsRemoved.push(a)));for(b=0;b<a.children.length;b++)this.removeChildRecurse(a.children[b])};THREE.Scene.prototype.addObject=THREE.Scene.prototype.addChild;
THREE.Scene.prototype.removeObject=THREE.Scene.prototype.removeChild;THREE.Scene.prototype.addLight=THREE.Scene.prototype.addChild;THREE.Scene.prototype.removeLight=THREE.Scene.prototype.removeChild;
THREE.CanvasRenderer=function(a){function b(a){if(r!=a)l.globalAlpha=r=a}function c(a){if(v!=a){switch(a){case THREE.NormalBlending:l.globalCompositeOperation="source-over";break;case THREE.AdditiveBlending:l.globalCompositeOperation="lighter";break;case THREE.SubtractiveBlending:l.globalCompositeOperation="darker"}v=a}}function d(a){if(V!=a)l.strokeStyle=V=a}function f(a){if(x!=a)l.fillStyle=x=a}var e=this,g=null,h=new THREE.Projector,a=a||{},k=a.canvas!==void 0?a.canvas:document.createElement("canvas"),
m,o,i,j,l=k.getContext("2d"),p=new THREE.Color(0),q=0,r=1,v=0,V=null,x=null,Q=null,y=null,C=null,n,t,u,E,T=new THREE.RenderableVertex,ba=new THREE.RenderableVertex,H,N,I,M,F,J,G,R,w,O,L,qa,D=new THREE.Color(0),s=new THREE.Color(0),B=new THREE.Color(0),z=new THREE.Color(0),K=new THREE.Color(0),Aa=[],P,U,Z,W,fa,ga,Fa,Ga,Ha,Ia,la=new THREE.Rectangle,$=new THREE.Rectangle,Y=new THREE.Rectangle,Ba=!1,ca=new THREE.Color,aa=new THREE.Color,ua=new THREE.Color,va=new THREE.Color,S=new THREE.Vector3,ra,sa,
Ca,da,ta,wa,a=16;ra=document.createElement("canvas");ra.width=ra.height=2;sa=ra.getContext("2d");sa.fillStyle="rgba(0,0,0,1)";sa.fillRect(0,0,2,2);Ca=sa.getImageData(0,0,2,2);da=Ca.data;ta=document.createElement("canvas");ta.width=ta.height=a;wa=ta.getContext("2d");wa.translate(-a/2,-a/2);wa.scale(a,a);a--;this.domElement=k;this.sortElements=this.sortObjects=this.autoClear=!0;this.data={vertices:0,faces:0};this.setSize=function(a,b){m=a;o=b;i=Math.floor(m/2);j=Math.floor(o/2);k.width=m;k.height=o;
la.set(-i,-j,i,j);$.set(-i,-j,i,j);r=1;v=0;C=y=Q=x=V=null};this.setClearColor=function(a,b){p.copy(a);q=b;$.set(-i,-j,i,j)};this.setClearColorHex=function(a,b){p.setHex(a);q=b;$.set(-i,-j,i,j)};this.clear=function(){l.setTransform(1,0,0,-1,i,j);$.isEmpty()||($.minSelf(la),$.inflate(2),q<1&&l.clearRect(Math.floor($.getX()),Math.floor($.getY()),Math.floor($.getWidth()),Math.floor($.getHeight())),q>0&&(c(THREE.NormalBlending),b(1),f("rgba("+Math.floor(p.r*255)+","+Math.floor(p.g*255)+","+Math.floor(p.b*
255)+","+q+")"),l.fillRect(Math.floor($.getX()),Math.floor($.getY()),Math.floor($.getWidth()),Math.floor($.getHeight()))),$.empty())};this.render=function(a,k){function m(a){var b,c,d,e=a.lights;aa.setRGB(0,0,0);ua.setRGB(0,0,0);va.setRGB(0,0,0);a=0;for(b=e.length;a<b;a++)c=e[a],d=c.color,c instanceof THREE.AmbientLight?(aa.r+=d.r,aa.g+=d.g,aa.b+=d.b):c instanceof THREE.DirectionalLight?(ua.r+=d.r,ua.g+=d.g,ua.b+=d.b):c instanceof THREE.PointLight&&(va.r+=d.r,va.g+=d.g,va.b+=d.b)}function o(a,b,c,
d){var e,f,g,h,l=a.lights,a=0;for(e=l.length;a<e;a++)f=l[a],g=f.color,f instanceof THREE.DirectionalLight?(h=c.dot(f.position),h<=0||(h*=f.intensity,d.r+=g.r*h,d.g+=g.g*h,d.b+=g.b*h)):f instanceof THREE.PointLight&&(h=c.dot(S.sub(f.position,b).normalize()),h<=0||(h*=f.distance==0?1:1-Math.min(b.distanceTo(f.position)/f.distance,1),h!=0&&(h*=f.intensity,d.r+=g.r*h,d.g+=g.g*h,d.b+=g.b*h)))}function p(a,e,g){b(g.opacity);c(g.blending);var h,k,o,n,Da,m;if(g instanceof THREE.ParticleBasicMaterial){if(g.map)n=
g.map.image,Da=n.width>>1,m=n.height>>1,g=e.scale.x*i,o=e.scale.y*j,h=g*Da,k=o*m,Y.set(a.x-h,a.y-k,a.x+h,a.y+k),la.instersects(Y)&&(l.save(),l.translate(a.x,a.y),l.rotate(-e.rotation),l.scale(g,-o),l.translate(-Da,-m),l.drawImage(n,0,0),l.restore())}else g instanceof THREE.ParticleCanvasMaterial&&(h=e.scale.x*i,k=e.scale.y*j,Y.set(a.x-h,a.y-k,a.x+h,a.y+k),la.instersects(Y)&&(d(g.color.getContextStyle()),f(g.color.getContextStyle()),l.save(),l.translate(a.x,a.y),l.rotate(-e.rotation),l.scale(h,k),
g.program(l),l.restore()))}function q(a,e,f,g){b(g.opacity);c(g.blending);l.beginPath();l.moveTo(a.positionScreen.x,a.positionScreen.y);l.lineTo(e.positionScreen.x,e.positionScreen.y);l.closePath();if(g instanceof THREE.LineBasicMaterial){a=g.linewidth;if(Q!=a)l.lineWidth=Q=a;a=g.linecap;if(y!=a)l.lineCap=y=a;a=g.linejoin;if(C!=a)l.lineJoin=C=a;d(g.color.getContextStyle());l.stroke();Y.inflate(g.linewidth*2)}}function r(a,d,f,g,h,l,i,j,n){e.data.vertices+=3;e.data.faces++;b(j.opacity);c(j.blending);
H=a.positionScreen.x;N=a.positionScreen.y;I=d.positionScreen.x;M=d.positionScreen.y;F=f.positionScreen.x;J=f.positionScreen.y;x(H,N,I,M,F,J);if(j instanceof THREE.MeshBasicMaterial)if(j.map)j.map.mapping instanceof THREE.UVMapping&&(W=i.uvs[0],Ea(H,N,I,M,F,J,W[g].u,W[g].v,W[h].u,W[h].v,W[l].u,W[l].v,j.map));else if(j.envMap){if(j.envMap.mapping instanceof THREE.SphericalReflectionMapping)a=k.matrixWorldInverse,S.copy(i.vertexNormalsWorld[0]),fa=(S.x*a.n11+S.y*a.n12+S.z*a.n13)*0.5+0.5,ga=-(S.x*a.n21+
S.y*a.n22+S.z*a.n23)*0.5+0.5,S.copy(i.vertexNormalsWorld[1]),Fa=(S.x*a.n11+S.y*a.n12+S.z*a.n13)*0.5+0.5,Ga=-(S.x*a.n21+S.y*a.n22+S.z*a.n23)*0.5+0.5,S.copy(i.vertexNormalsWorld[2]),Ha=(S.x*a.n11+S.y*a.n12+S.z*a.n13)*0.5+0.5,Ia=-(S.x*a.n21+S.y*a.n22+S.z*a.n23)*0.5+0.5,Ea(H,N,I,M,F,J,fa,ga,Fa,Ga,Ha,Ia,j.envMap)}else j.wireframe?ha(j.color,j.wireframeLinewidth,j.wireframeLinecap,j.wireframeLinejoin):ia(j.color);else if(j instanceof THREE.MeshLambertMaterial)j.map&&!j.wireframe&&(j.map.mapping instanceof
THREE.UVMapping&&(W=i.uvs[0],Ea(H,N,I,M,F,J,W[g].u,W[g].v,W[h].u,W[h].v,W[l].u,W[l].v,j.map)),c(THREE.SubtractiveBlending)),Ba?!j.wireframe&&j.shading==THREE.SmoothShading&&i.vertexNormalsWorld.length==3?(s.r=B.r=z.r=aa.r,s.g=B.g=z.g=aa.g,s.b=B.b=z.b=aa.b,o(n,i.v1.positionWorld,i.vertexNormalsWorld[0],s),o(n,i.v2.positionWorld,i.vertexNormalsWorld[1],B),o(n,i.v3.positionWorld,i.vertexNormalsWorld[2],z),K.r=(B.r+z.r)*0.5,K.g=(B.g+z.g)*0.5,K.b=(B.b+z.b)*0.5,Z=xa(s,B,z,K),na(H,N,I,M,F,J,0,0,1,0,0,1,
Z)):(ca.r=aa.r,ca.g=aa.g,ca.b=aa.b,o(n,i.centroidWorld,i.normalWorld,ca),D.r=Math.max(0,Math.min(j.color.r*ca.r,1)),D.g=Math.max(0,Math.min(j.color.g*ca.g,1)),D.b=Math.max(0,Math.min(j.color.b*ca.b,1)),j.wireframe?ha(D,j.wireframeLinewidth,j.wireframeLinecap,j.wireframeLinejoin):ia(D)):j.wireframe?ha(j.color,j.wireframeLinewidth,j.wireframeLinecap,j.wireframeLinejoin):ia(j.color);else if(j instanceof THREE.MeshDepthMaterial)P=k.near,U=k.far,s.r=s.g=s.b=1-ma(a.positionScreen.z,P,U),B.r=B.g=B.b=1-ma(d.positionScreen.z,
P,U),z.r=z.g=z.b=1-ma(f.positionScreen.z,P,U),K.r=(B.r+z.r)*0.5,K.g=(B.g+z.g)*0.5,K.b=(B.b+z.b)*0.5,Z=xa(s,B,z,K),na(H,N,I,M,F,J,0,0,1,0,0,1,Z);else if(j instanceof THREE.MeshNormalMaterial)D.r=oa(i.normalWorld.x),D.g=oa(i.normalWorld.y),D.b=oa(i.normalWorld.z),j.wireframe?ha(D,j.wireframeLinewidth,j.wireframeLinecap,j.wireframeLinejoin):ia(D)}function v(a,d,f,g,h,l,j,i,n){e.data.vertices+=4;e.data.faces++;b(i.opacity);c(i.blending);if(i.map||i.envMap)r(a,d,g,0,1,3,j,i,n),r(h,f,l,1,2,3,j,i,n);else if(H=
a.positionScreen.x,N=a.positionScreen.y,I=d.positionScreen.x,M=d.positionScreen.y,F=f.positionScreen.x,J=f.positionScreen.y,G=g.positionScreen.x,R=g.positionScreen.y,w=h.positionScreen.x,O=h.positionScreen.y,L=l.positionScreen.x,qa=l.positionScreen.y,i instanceof THREE.MeshBasicMaterial)V(H,N,I,M,F,J,G,R),i.wireframe?ha(i.color,i.wireframeLinewidth,i.wireframeLinecap,i.wireframeLinejoin):ia(i.color);else if(i instanceof THREE.MeshLambertMaterial)Ba?!i.wireframe&&i.shading==THREE.SmoothShading&&j.vertexNormalsWorld.length==
4?(s.r=B.r=z.r=K.r=aa.r,s.g=B.g=z.g=K.g=aa.g,s.b=B.b=z.b=K.b=aa.b,o(n,j.v1.positionWorld,j.vertexNormalsWorld[0],s),o(n,j.v2.positionWorld,j.vertexNormalsWorld[1],B),o(n,j.v4.positionWorld,j.vertexNormalsWorld[3],z),o(n,j.v3.positionWorld,j.vertexNormalsWorld[2],K),Z=xa(s,B,z,K),x(H,N,I,M,G,R),na(H,N,I,M,G,R,0,0,1,0,0,1,Z),x(w,O,F,J,L,qa),na(w,O,F,J,L,qa,1,0,1,1,0,1,Z)):(ca.r=aa.r,ca.g=aa.g,ca.b=aa.b,o(n,j.centroidWorld,j.normalWorld,ca),D.r=Math.max(0,Math.min(i.color.r*ca.r,1)),D.g=Math.max(0,Math.min(i.color.g*
ca.g,1)),D.b=Math.max(0,Math.min(i.color.b*ca.b,1)),V(H,N,I,M,F,J,G,R),i.wireframe?ha(D,i.wireframeLinewidth,i.wireframeLinecap,i.wireframeLinejoin):ia(D)):(V(H,N,I,M,F,J,G,R),i.wireframe?ha(i.color,i.wireframeLinewidth,i.wireframeLinecap,i.wireframeLinejoin):ia(i.color));else if(i instanceof THREE.MeshNormalMaterial)D.r=oa(j.normalWorld.x),D.g=oa(j.normalWorld.y),D.b=oa(j.normalWorld.z),V(H,N,I,M,F,J,G,R),i.wireframe?ha(D,i.wireframeLinewidth,i.wireframeLinecap,i.wireframeLinejoin):ia(D);else if(i instanceof
THREE.MeshDepthMaterial)P=k.near,U=k.far,s.r=s.g=s.b=1-ma(a.positionScreen.z,P,U),B.r=B.g=B.b=1-ma(d.positionScreen.z,P,U),z.r=z.g=z.b=1-ma(g.positionScreen.z,P,U),K.r=K.g=K.b=1-ma(f.positionScreen.z,P,U),Z=xa(s,B,z,K),x(H,N,I,M,G,R),na(H,N,I,M,G,R,0,0,1,0,0,1,Z),x(w,O,F,J,L,qa),na(w,O,F,J,L,qa,1,0,1,1,0,1,Z)}function x(a,b,c,d,e,f){l.beginPath();l.moveTo(a,b);l.lineTo(c,d);l.lineTo(e,f);l.lineTo(a,b);l.closePath()}function V(a,b,c,d,e,f,g,h){l.beginPath();l.moveTo(a,b);l.lineTo(c,d);l.lineTo(e,f);
l.lineTo(g,h);l.lineTo(a,b);l.closePath()}function ha(a,b,c,e){if(Q!=b)l.lineWidth=Q=b;if(y!=c)l.lineCap=y=c;if(C!=e)l.lineJoin=C=e;d(a.getContextStyle());l.stroke();Y.inflate(b*2)}function ia(a){f(a.getContextStyle());l.fill()}function Ea(a,b,c,d,e,g,h,i,j,k,n,o,m){if(m.image.width!=0){if(m.needsUpdate==!0||Aa[m.id]==void 0){var p=m.wrapS==THREE.RepeatWrapping,q=m.wrapT==THREE.RepeatWrapping;Aa[m.id]=l.createPattern(m.image,p&&q?"repeat":p&&!q?"repeat-x":!p&&q?"repeat-y":"no-repeat");m.needsUpdate=
!1}f(Aa[m.id]);var p=m.offset.x/m.repeat.x,q=m.offset.y/m.repeat.y,r=(m.image.width-1)*m.repeat.x,m=(m.image.height-1)*m.repeat.y,h=(h+p)*r,i=(i+q)*m,j=(j+p)*r,k=(k+q)*m,n=(n+p)*r,o=(o+q)*m;c-=a;d-=b;e-=a;g-=b;j-=h;k-=i;n-=h;o-=i;p=1/(j*o-n*k);m=(o*c-k*e)*p;k=(o*d-k*g)*p;c=(j*e-n*c)*p;d=(j*g-n*d)*p;a=a-m*h-c*i;b=b-k*h-d*i;l.save();l.transform(m,k,c,d,a,b);l.fill();l.restore()}}function na(a,b,c,d,e,f,g,h,i,j,k,m,n){var o,p;o=n.width-1;p=n.height-1;g*=o;h*=p;i*=o;j*=p;k*=o;m*=p;c-=a;d-=b;e-=a;f-=b;
i-=g;j-=h;k-=g;m-=h;p=1/(i*m-k*j);o=(m*c-j*e)*p;j=(m*d-j*f)*p;c=(i*e-k*c)*p;d=(i*f-k*d)*p;a=a-o*g-c*h;b=b-j*g-d*h;l.save();l.transform(o,j,c,d,a,b);l.clip();l.drawImage(n,0,0);l.restore()}function xa(a,b,c,d){var e=~~(a.r*255),f=~~(a.g*255),a=~~(a.b*255),g=~~(b.r*255),h=~~(b.g*255),b=~~(b.b*255),i=~~(c.r*255),j=~~(c.g*255),c=~~(c.b*255),k=~~(d.r*255),l=~~(d.g*255),d=~~(d.b*255);da[0]=e<0?0:e>255?255:e;da[1]=f<0?0:f>255?255:f;da[2]=a<0?0:a>255?255:a;da[4]=g<0?0:g>255?255:g;da[5]=h<0?0:h>255?255:h;
da[6]=b<0?0:b>255?255:b;da[8]=i<0?0:i>255?255:i;da[9]=j<0?0:j>255?255:j;da[10]=c<0?0:c>255?255:c;da[12]=k<0?0:k>255?255:k;da[13]=l<0?0:l>255?255:l;da[14]=d<0?0:d>255?255:d;sa.putImageData(Ca,0,0);wa.drawImage(ra,0,0);return ta}function ma(a,b,c){a=(a-b)/(c-b);return a*a*(3-2*a)}function oa(a){a=(a+1)*0.5;return a<0?0:a>1?1:a}function ja(a,b){var c=b.x-a.x,d=b.y-a.y,e=c*c+d*d;e!=0&&(e=1/Math.sqrt(e),c*=e,d*=e,b.x+=c,b.y+=d,a.x-=c,a.y-=d)}var ya,Ja,A,ea,ka,pa,za,X;this.autoClear?this.clear():l.setTransform(1,
0,0,-1,i,j);e.data.vertices=0;e.data.faces=0;g=h.projectScene(a,k,this.sortElements);(Ba=a.lights.length>0)&&m(a);ya=0;for(Ja=g.length;ya<Ja;ya++){A=g[ya];Y.empty();if(A instanceof THREE.RenderableParticle){n=A;n.x*=i;n.y*=j;ea=0;for(ka=A.materials.length;ea<ka;)X=A.materials[ea++],X.opacity!=0&&p(n,A,X,a)}else if(A instanceof THREE.RenderableLine){if(n=A.v1,t=A.v2,n.positionScreen.x*=i,n.positionScreen.y*=j,t.positionScreen.x*=i,t.positionScreen.y*=j,Y.addPoint(n.positionScreen.x,n.positionScreen.y),
Y.addPoint(t.positionScreen.x,t.positionScreen.y),la.instersects(Y)){ea=0;for(ka=A.materials.length;ea<ka;)X=A.materials[ea++],X.opacity!=0&&q(n,t,A,X,a)}}else if(A instanceof THREE.RenderableFace3){if(n=A.v1,t=A.v2,u=A.v3,n.positionScreen.x*=i,n.positionScreen.y*=j,t.positionScreen.x*=i,t.positionScreen.y*=j,u.positionScreen.x*=i,u.positionScreen.y*=j,A.overdraw&&(ja(n.positionScreen,t.positionScreen),ja(t.positionScreen,u.positionScreen),ja(u.positionScreen,n.positionScreen)),Y.add3Points(n.positionScreen.x,
n.positionScreen.y,t.positionScreen.x,t.positionScreen.y,u.positionScreen.x,u.positionScreen.y),la.instersects(Y)){ea=0;for(ka=A.meshMaterials.length;ea<ka;)if(X=A.meshMaterials[ea++],X instanceof THREE.MeshFaceMaterial){pa=0;for(za=A.faceMaterials.length;pa<za;)(X=A.faceMaterials[pa++])&&X.opacity!=0&&r(n,t,u,0,1,2,A,X,a)}else X.opacity!=0&&r(n,t,u,0,1,2,A,X,a)}}else if(A instanceof THREE.RenderableFace4&&(n=A.v1,t=A.v2,u=A.v3,E=A.v4,n.positionScreen.x*=i,n.positionScreen.y*=j,t.positionScreen.x*=
i,t.positionScreen.y*=j,u.positionScreen.x*=i,u.positionScreen.y*=j,E.positionScreen.x*=i,E.positionScreen.y*=j,T.positionScreen.copy(t.positionScreen),ba.positionScreen.copy(E.positionScreen),A.overdraw&&(ja(n.positionScreen,t.positionScreen),ja(t.positionScreen,E.positionScreen),ja(E.positionScreen,n.positionScreen),ja(u.positionScreen,T.positionScreen),ja(u.positionScreen,ba.positionScreen)),Y.addPoint(n.positionScreen.x,n.positionScreen.y),Y.addPoint(t.positionScreen.x,t.positionScreen.y),Y.addPoint(u.positionScreen.x,
u.positionScreen.y),Y.addPoint(E.positionScreen.x,E.positionScreen.y),la.instersects(Y))){ea=0;for(ka=A.meshMaterials.length;ea<ka;)if(X=A.meshMaterials[ea++],X instanceof THREE.MeshFaceMaterial){pa=0;for(za=A.faceMaterials.length;pa<za;)(X=A.faceMaterials[pa++])&&X.opacity!=0&&v(n,t,u,E,T,ba,A,X,a)}else X.opacity!=0&&v(n,t,u,E,T,ba,A,X,a)}$.addRectangle(Y)}l.setTransform(1,0,0,1,0,0)}};
THREE.RenderableVertex=function(){this.positionWorld=new THREE.Vector3;this.positionScreen=new THREE.Vector4;this.visible=!0};THREE.RenderableVertex.prototype.copy=function(a){this.positionWorld.copy(a.positionWorld);this.positionScreen.copy(a.positionScreen)};
THREE.RenderableFace3=function(){this.v1=new THREE.RenderableVertex;this.v2=new THREE.RenderableVertex;this.v3=new THREE.RenderableVertex;this.centroidWorld=new THREE.Vector3;this.centroidScreen=new THREE.Vector3;this.normalWorld=new THREE.Vector3;this.vertexNormalsWorld=[new THREE.Vector3,new THREE.Vector3,new THREE.Vector3];this.faceMaterials=this.meshMaterials=null;this.overdraw=!1;this.uvs=[[]];this.z=null};
THREE.RenderableFace4=function(){this.v1=new THREE.RenderableVertex;this.v2=new THREE.RenderableVertex;this.v3=new THREE.RenderableVertex;this.v4=new THREE.RenderableVertex;this.centroidWorld=new THREE.Vector3;this.centroidScreen=new THREE.Vector3;this.normalWorld=new THREE.Vector3;this.vertexNormalsWorld=[new THREE.Vector3,new THREE.Vector3,new THREE.Vector3,new THREE.Vector3];this.faceMaterials=this.meshMaterials=null;this.overdraw=!1;this.uvs=[[]];this.z=null};
THREE.RenderableObject=function(){this.z=this.object=null};THREE.RenderableParticle=function(){this.rotation=this.z=this.y=this.x=null;this.scale=new THREE.Vector2;this.materials=null};THREE.RenderableLine=function(){this.z=null;this.v1=new THREE.RenderableVertex;this.v2=new THREE.RenderableVertex;this.materials=null};
